refactor(asynceapi): Use http head request to check_connection
aristanetworks/anta pull request #851
Opened 2024-10-04 16:11 UTC by dlobato

# Description

Use HTTP HEAD request to check connection to a device instead of pure L3 check.
This allows to check connectivity on devices behind a reverse proxy, so rather than checking the reverse proxy is alive using HTTP the request will be forwarded to the right device.

The change is as close to the original as possible, but we could potentially check if the credentials are correct as well.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-10-10 15:53 UTC, mtache requested changes
Hi David,

_This changes the current behaviour, hence changing the PR name._

I understand that your use case is to actually check that eAPI is reachable behind a reverse proxy which is not possible today with the simple call to `asyncio.open_connection()`.

I checked the behaviour of a HEAD request on the base_url and here is the result:
```
$ curl -k --head https://172.20.1.3
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 10 Oct 2024 15:34:22 GMT
Content-Type: text/html
Content-Length: 13
Connection: keep-alive
Location: https://172.20.1.3/eapi/
```

`https://172.20.1.3/eapi/` is actually the eAPI Explorer.
So we can either do that, expect and 301 and test the redirect URL (https://www.python-httpx.org/quickstart/#redirection-and-history)

Or we can do a HEAD on `https://{base_url}/command-api` and expect a 401 if not authenticated:
```
$ curl -k --head https://172.20.1.3/command-api
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Thu, 10 Oct 2024 15:38:59 GMT
Content-Type: text/plain
Content-Length: 30
Connection: keep-alive
```
I assume the code should also expect a 200 if the `asynceapi.Device` instance is authenticated.

Please update the code to handle that behaviour and write unit tests :)

Regarding login, I like the idea of checking the credentials before sending the "show version" eAPI request like we do today. I've opened #871 to track this.

Thanks !

2024-10-11 10:40 UTC, dlobato commented
Hi Matthieu,

I also think that requesting headers from command-api would be better. Since we have the credentials we can then check the status code and conclude if we can actually connect to the eAPI server.

I'll update the code and add the required tests.

David

2025-04-08 17:32 UTC, carl-baillargeon reviewed
@gmuloc I am ok with merging this (after fixing my review comments) in a minor release but please confirm and consider the following for `refresh`:

1- Currently, `is_online` could be `True` even if subsequent commands failed due to HTTP errors (like 401 Unauthorized). Now, such errors will cause `is_online` to be `False` right away.

2- Errors like 401, 500 are detected _before_ attempting `show version`, whereas before they were detected _after_ the `_collect(show_version)` failed.

3- The warning message associated with these failures changes from potentially `Cannot get hardware information...` (if `_collect` failed) to the new `Could not connect... eAPI endpoint: [Error details]`.

4- Because of this, `self.established` will become `False` earlier and for more reasons (HTTP errors during the initial check) than before.

To me it's arguably an improvement/fix but I will let you chime in.

2025-04-08 17:32 UTC, carl-baillargeon commented on asynceapi/aio_portcheck.py
Let's keep this module as is to avoid a breaking change.

2025-04-08 17:32 UTC, carl-baillargeon commented on asynceapi/device.py
> +        return True
This is a breaking change because we are raising instead or returning False. Let's keep this method as is and create a new one called `check_api_endpoint` with this logic.

2025-04-08 17:32 UTC, carl-baillargeon commented on anta/device.py
> +
Here we can use `self._session.check_api_endpoint()` instead (see my other comment).

2025-04-09 08:10 UTC, dlobato commented on anta/device.py
> +
done

2025-04-09 15:47 UTC, gmuloc approved these changes

2025-04-09 15:47 UTC, carl-baillargeon approved these changes
LGTM.

2025-04-09 16:07 UTC, merged