refactor(anta): Refactor the VerifyBFDPeersIntervals test to add detection time
aristanetworks/anta pull request #858
Opened 2024-10-08 04:37 UTC by vitthalmagadum

# Description
Verifies the timers of the IPv4 BFD peers in the specified VRF.

    Expected Results
    ----------------
    * Success: The test will pass if the timers of the IPv4 BFD peers are correct in the specified VRF.
    * Failure: The test will fail if the IPv4 BFD peers are not found or their timers are incorrect in the specified VRF.

Fixes #857 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2025-01-07 19:09 UTC, carl-baillargeon requested changes

2025-01-07 19:09 UTC, carl-baillargeon commented on anta/input_models/bfd.py
> +    after which the session is determined to have failed."""
```suggestion
    """Detection time of BFD peer in milliseconds. Defines how long to wait without receiving BFD packets before declaring the peer session as down.
    
    Optional field in the `VerifyBFDPeersIntervals` test.
    """
```
Please update the test logic + docstring to accomodate this optional field (to avoid breaking changes).

2025-01-07 19:09 UTC, carl-baillargeon commented on anta/tests/bfd.py
> +            detect_time = bfd_peer.detection_time
We should add a `@field_validator` in Input to check that `tx_interval`, `rx_interval` and `multipler` are provided, similar to what we do with `BgpPeer`. Previous behaviour: https://github.com/aristanetworks/anta/pull/926/files#diff-ea769c2163365318e4e31c317a8c772e6bf95083314abc9ae8c3f493d30b515cL141-L146

`detect_time` should be optional to avoid breaking changes.

2025-01-07 19:09 UTC, carl-baillargeon commented on anta/tests/bfd.py
> +            detect_time = bfd_peer.detection_time
We should also update/fix the other BFD tests with proper validators (in a separate PR).

2025-01-08 10:59 UTC, vitthalmagadum commented on anta/input_models/bfd.py
> +    after which the session is determined to have failed."""
Updated. Thanks!!

2025-01-08 11:00 UTC, vitthalmagadum commented on anta/tests/bfd.py
> +            detect_time = bfd_peer.detection_time
addressed this in `https://github.com/aristanetworks/anta/pull/999`.
Thanks!!

2025-01-08 13:22 UTC, merged