feat(anta): Added the test case to verify SNMP groups
aristanetworks/anta pull request #886
Opened 2024-10-16 18:19 UTC by vitthalmagadum

# Description

Verifies the SNMP group configurations for specified version(s).

    - Verifies that the valid group name and security model version.
    - Ensures that the SNMP views, the read, write and notify settings aligning with version-specific requirements.

    Expected Results
    ----------------
    * Success: The test will pass if the provided SNMP group and all specified parameters are correctly configured.
    * Failure: The test will fail if the provided SNMP group is not configured or specified parameters are not correctly configured.

Fixes #853 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2025-01-21 00:09 UTC, carl-baillargeon requested changes

2025-01-21 00:09 UTC, carl-baillargeon commented on anta/tests/snmp.py
> +                )
You could simplify this logic by looping over read, write, notify. Something like:
```python
for view_type in ["read", "write", "notify"]:
    expected_view = getattr(group, f"{view_type}_view")
    if expected_view and not all([
        (act_view := group_details.get(f"{view_type}View")) == expected_view,
        (view_configured := group_details.get(f"{view_type}ViewConfig"))
    ]):
        self.result.is_failure(
            f"{group} {view_type.title()} View: {expected_view} - "
            f"View configuration mismatch - {view_type.title()} View: {act_view}, "
            f"Configured: {view_configured}"
        )
```

2025-01-21 00:09 UTC, carl-baillargeon commented on anta/tests/snmp.py
> +                )
Also, since `group_details.get()` could return an empty string, we should handle it in the failure message to avoid having something empty. You should also add a unit test for an output with it:
```json
{
    "groups": {
        "ARISTA_SNMPV3_RO_GROUP": {
            "versions": {
                "v3": {
                    "secModel": "v3Priv",
                    "readView": "ARISTA_FULL_SNMP_TREE_VIEW",
                    "readViewConfig": true,
                    "writeView": "",  # Empty string
                    "notifyView": ""
                }
            }
        }
    }
}
```

2025-01-21 08:14 UTC, geetanjalimanegslab commented on anta/input_models/snmp.py
> +    - v3NoAuth: Group using neither authentication nor privacy
Hi, Carl, Yes agreed, we already have default column, hence remove the string, Defaults to None,
Also regarding the content rendering in the doc, I have tried modifying the content  in a multiple ways, but in the document it is not rendering properly. hence for now I have remove the informative strings from the description. please share your thoughts on the same.

Thanks 
Geetanjali

2025-01-21 08:15 UTC, geetanjalimanegslab commented on anta/tests/snmp.py
> +                )
Yeah!.. Thanks alot @carl-baillargeon  for the suggestion, I have updated testcase with the above logic and added UT for the empty string check.

2025-01-21 22:06 UTC, gmuloc requested changes
@carl-baillargeon let us know if you disagree with splitting the error messages

2025-01-21 22:06 UTC, gmuloc commented on anta/tests/snmp.py
> +    * Failure: The test will fail if the provided SNMP group is not configured or specified parameters are not correctly configured.
```suggestion
    * Failure: The test will fail if the provided SNMP group is not configured or if any specified parameter is not correctly configured.
```

2025-01-21 22:06 UTC, gmuloc commented on anta/tests/snmp.py
> +            - group_name: Group1
show other versions in example - especially with the security model for v3

2025-01-21 22:06 UTC, gmuloc commented on anta/tests/snmp.py
> +                    msg = f"{snmp_group}; `authentication` field is required for `version: v3`"
Please don't use semi columns

```suggestion
                    msg = f"{snmp_group}: `authentication` field is required for `version: v3`"
```

2025-01-21 22:06 UTC, gmuloc commented on anta/tests/snmp.py
> +                    )
I would rather make two error messages, 1 to indicate the view name is not correct (matcging the expecting one) and 2. to indicate that when the view name is matching, it is not properly configured (Configured: False)

2025-01-22 02:28 UTC, carl-baillargeon commented on anta/tests/snmp.py
> +                    )
Agreed

2025-01-28 13:34 UTC, gmuloc commented on anta/input_models/snmp.py
> +    """SNMPv3 authentication settings. Required when version is v3."""
how is it made required?

2025-01-28 13:34 UTC, gmuloc commented on anta/input_models/snmp.py
> +    """SNMPv3 authentication settings. Required when version is v3."""
ok only in the test so maybe indicate it is for a given test

2025-01-28 13:34 UTC, gmuloc commented on anta/input_models/snmp.py
> +    """SNMPv3 authentication settings. Required when version is v3."""
actually probably best to just add a validator in the SnmpGroup rather trhan in the test - what do you think?

2025-01-29 06:47 UTC, geetanjalimanegslab commented on anta/input_models/snmp.py
> +    """SNMPv3 authentication settings. Required when version is v3."""
Agreed with your point @gmuloc , Thanks for the suggestion, updated testcase accordingly.

2025-02-06 19:34 UTC, carl-baillargeon commented on anta/input_models/snmp.py
> +    """Model for a SNMP group."""
```suggestion
    """Model for an SNMP group."""
```

2025-02-06 20:08 UTC, carl-baillargeon commented on anta/custom_types.py
> +def snmp_v3_prefix(auth_type: str) -> str:
Fixed in eaeb32988be4514392ab1328d0f94dcb2ae5a4df

2025-02-06 20:08 UTC, carl-baillargeon approved these changes
LGTM!

2025-02-06 20:18 UTC, merged