fix(anta.tests): Cleaning up security tests module (VerifyAPISSLCertificate, VerifyIPv4ACL)
aristanetworks/anta pull request #957
Opened 2024-12-09 13:22 UTC by vitthalmagadum

# Description

Refactoring security tests module to address the following issues:

- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have run pre-commit for code linting and typing (`pre-commit run`)
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-12-12 09:39 UTC, gmuloc requested changes
Please add a test for coverage

![Screenshot 2024-12-12 at 10 38 51](https://github.com/user-attachments/assets/2ee762d0-5d25-45bf-937b-250f70205b5c)

2024-12-18 21:23 UTC, gmuloc submitted a review, later dismissed

2024-12-18 21:23 UTC, gmuloc commented on tests/units/anta_tests/test_security.py
> +                        "notAfter": 1705992709,
out of curiosity, why did you need to change this?

2024-12-18 21:23 UTC, gmuloc commented on anta/tests/security.py
> +        - The any IPv4 ACL entry is not configured.
```suggestion
        - Any IPv4 ACL entry is not configured.
```

2024-12-18 21:23 UTC, gmuloc commented on anta/tests/security.py
> +      2. Validates that the certificate's common name matches the expected subject name.
```suggestion
      2. Validates that the certificate Common Name matches the expected one.
```

2024-12-18 21:23 UTC, gmuloc commented on anta/tests/security.py
> +      4. Verifies the certificate's key size aligns with the encryption algorithm's requirements.
The key size on the device cannot "not align" with the encryption algorithm requirement. We in ANTA are checking that people cannot enters absurd inputs by checking that the key size is possible with the encryption algo. But thats not what the test is checking.

 
```suggestion
      4. Verifies the certificate key matches the expected key size.
```

2024-12-18 21:23 UTC, gmuloc commented on anta/tests/security.py
> +        - The key size does not meet security standards.
Fix based on the comments above

2024-12-18 21:23 UTC, gmuloc commented on anta/input_models/security.py
> +    """The common subject name of the certificate."""
The capitalized words have a meaning in certificate world (CN)
```suggestion
    """The Common Name of the certificate."""
```

2024-12-18 21:23 UTC, gmuloc commented on anta/tests/security.py
> +      2. Validates that the sequence entries in the ACL are correctly ordered.
Lets not change it here but given the model I feel like we also support IPv6 in this test. @carl-baillargeon

2025-01-13 08:26 UTC, vitthalmagadum commented on tests/units/anta_tests/test_security.py
> +                        "notAfter": 1705992709,
Just for desired message, I have updated this

2025-01-13 08:26 UTC, vitthalmagadum commented on anta/tests/security.py
> +        - The any IPv4 ACL entry is not configured.
Updated

2025-01-13 08:26 UTC, vitthalmagadum commented on anta/tests/security.py
> +      2. Validates that the certificate's common name matches the expected subject name.
Updated

2025-01-13 08:27 UTC, vitthalmagadum commented on anta/tests/security.py
> +      4. Verifies the certificate's key size aligns with the encryption algorithm's requirements.
Updated

2025-01-13 08:27 UTC, vitthalmagadum commented on anta/tests/security.py
> +        - The key size does not meet security standards.
Updated

2025-01-13 08:27 UTC, vitthalmagadum commented on anta/input_models/security.py
> +    """The common subject name of the certificate."""
Updated

2025-01-14 20:50 UTC, carl-baillargeon commented on anta/input_models/security.py
> +    """
```suggestion
    """Action of the ACL entry. Example: `deny ip any any`."""
```

2025-01-14 20:50 UTC, carl-baillargeon commented on anta/input_models/security.py
> +    """The unique sequence number of the ACL entry, used to define the order of processing. Must be between 1 and 4294967295."""
```suggestion
    """Sequence number of the ACL entry, used to define the order of processing. Must be between 1 and 4294967295."""
```

2025-01-14 20:50 UTC, carl-baillargeon commented on anta/tests/security.py
> +      2. Validates that the sequence entries in the ACL are correctly ordered.
`ACL` model (same goes for `IPv4ACL`) does support IPv6 entries since the action is just a string so we cannot really differentiate between `deny ipv6 any any` and `deny ip any any` but the command is actually `show ip access-lists` and not `show ipv6 access-lists` so we are good when we say we verify IPv4 ACLs. If a user provides an IPv6 related entry if will just fail.

If we decide to create `VerifyIPv6ACL` later we could use the same `ACL` model just fine.

2025-01-15 09:13 UTC, vitthalmagadum commented on anta/input_models/security.py
> +    """
Updated.

2025-01-15 09:14 UTC, vitthalmagadum commented on anta/input_models/security.py
> +    """The unique sequence number of the ACL entry, used to define the order of processing. Must be between 1 and 4294967295."""
Updated.

2025-01-15 13:44 UTC, carl-baillargeon commented on anta/tests/security.py
> +      2. Validates that the sequence entries in the ACL are correctly ordered.
@gmuloc Did you want to change something based on this?

2025-01-15 14:19 UTC, carl-baillargeon approved these changes
LGTM if CI passes.

2025-01-15 14:49 UTC, gmuloc commented on anta/tests/security.py
> +      2. Validates that the sequence entries in the ACL are correctly ordered.
nope thats ok

2025-01-15 14:49 UTC, merged