fix(anta.tests): Cleaning up ISIS tests module
aristanetworks/anta pull request #963
Opened 2024-12-10 18:13 UTC by vitthalmagadum

# Description

Refactoring ISIS tests module to address the following issues:

- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

2024-12-12 19:07 UTC, carl-baillargeon commented on tests/units/anta_tests/routing/test_isis.py
> +                "Instance: CORE-ISIS VRF: default Interface: Ethernet2 Endpoint: 10.0.1.3 - Not correctly configured - Origin: dynamic Endpoint: 10.0.1.3 Level: 2"
Can we put Expected and Actual here?

2024-12-18 05:05 UTC, vitthalmagadum commented on tests/units/anta_tests/routing/test_isis.py
> +                "Instance: CORE-ISIS VRF: default Interface: Ethernet2 Endpoint: 10.0.1.3 - Not correctly configured - Origin: dynamic Endpoint: 10.0.1.3 Level: 2"
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/tests/routing/isis.py
> +                    self.result.is_failure(f"{interface} - Incorrect mode - Expected: point-to-point Actual: {interface_type}")
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +    """The operational mode of the IS-IS interface."""
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +    """Model for a ISIS Interface."""
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +        return f"Interface: {self.interface} Endpoint: {self.address}"
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +    """A list of IS-IS segments associated with the instance. Required field in the `VerifyISISSegmentRoutingDataplane` test"""
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +    """Configured dataplane for the IS-IS instance."""
Updated

2024-12-18 05:05 UTC, vitthalmagadum commented on anta/input_models/routing/isis.py
> +    """Model for a ISIS instance."""
Updated

2024-12-20 13:09 UTC, gmuloc commented
Please add coverage

![Screenshot 2024-12-20 at 14 09 13](https://github.com/user-attachments/assets/1f4bb5a1-8fa7-4b19-8884-4d2791ba7725)

2025-01-04 18:42 UTC, carl-baillargeon requested changes

2025-01-04 18:42 UTC, carl-baillargeon commented on anta/tests/routing/isis.py
> +      2. Validates the number of IS-IS neighbors for each interface at specified level.
Same as VerifyISISNeighborState, we should use `show isis interface brief vrf all` command instead.

2025-01-04 18:42 UTC, carl-baillargeon commented on anta/tests/routing/isis.py
> +      2. Validates the operational mode of each IS-IS interface (e.g., "active," "passive," or "unset").
Same as others: `show isis interface brief vrf all` :). It's actually a bug for this test so let's fix it!

2025-01-04 18:42 UTC, carl-baillargeon commented on anta/tests/routing/isis.py
> +        instances: list[ISISInstance]
IS-IS SR is only supported in default VRF.

On EOS:
```
PE11(config-router-isis-vrf-DEV)#segment-routing mpls 
% Unavailable command (not supported in non-default vrf)
```

We should add a Pydantic validator here to check if the VRF in each `ISISInstance` model is left to `default`. If not, we can raise an error and say that as of 4.33.1F, IS-IS SR is only supported in default VRF. Refer to https://www.arista.com/en/support/toi/eos-4-17-0f/13789-isis-segment-routing in the limitations section.

2025-01-04 18:42 UTC, carl-baillargeon commented on anta/tests/routing/isis.py
> +        instances: list[ISISInstance]
Same comment as above about ISIS SR supported in default VRF only.

2025-02-06 18:42 UTC, carl-baillargeon approved these changes
LGTM. Thanks Vitthal

2025-02-06 18:42 UTC, merged