fix(anta.tests): Cleaning up flow-tracking tests module
aristanetworks/anta pull request #964
Opened 2024-12-12 11:38 UTC by vitthalmagadum

# Description

Refactoring flow-tracking tests module to address the following issues:

- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have run pre-commit for code linting and typing (`pre-commit run`)
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2025-01-14 14:50 UTC, gmuloc requested changes

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
>          Failure message if any exporter configuration does not match.
```suggestion
        List of failure messages for any exporter configuration that does not match.
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +    failed_log = []
+ edit where needed
```suggestion
    failure_messages = []
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +    """Verifies the hardware flow tracking.
```suggestion
    """Verifies the hardware flow tracking configuration.
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +      2. Confirms that the specified input tracker is active.
only one tracker?
```suggestion
      2. Confirms that the specified input tracker is active.
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +        - All Hardware flow tracking is running.
Not sure what this means
```suggestion
        - All Hardware flow tracking is running.
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +    commands: ClassVar[list[AntaCommand | AntaTemplate]] = [AntaCommand(command="show flow tracking hardware", revision=2)]
whats the purpose of changing revision? (not saying it is bad but just wondering)

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +        - The specified input tracker is not active.
There is a list of input trackerS -> this success / failure criteria should make this clear. please reword with something like:

for each expected tracker ...

2025-01-14 14:50 UTC, gmuloc commented on anta/input_models/flow_tracking.py
> +        return f"InActive Timeout: {self.on_inactive_timeout} Active Interval: {self.on_interval}"
```suggestion
        return f"Inactive Timeout: {self.on_inactive_timeout}, Active Interval: {self.on_interval}"
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +            failed_log.append(f"Exporter: {exporter_name} - Incorrect template interval - Expected: {exporter.template_interval} Actual: {template_interval}")
```suggestion
            failed_log.append(f"Exporter: {exporter_name} - Incorrect template interval - Expected: {exporter.template_interval}, Actual: {template_interval}")
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +                        f"{tracker} {tracker.record_export} - Incorrect durations - InActive Timeout: {act_inactive} OnActive Interval: {act_interval}"
missing the actual / expected so we don't know what value we are getting from this lg message
```suggestion
                        f"{tracker} {tracker.record_export} - Incorrect durations - InActive Timeout: {act_inactive}, OnActive Interval: {act_interval}"
```

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +                    self.result.is_failure(f"{tracker} {log}")
maybe this need some nice formatting

2025-01-14 14:50 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +                failed_log = validate_exporters(tracker.exporters, tracker_info)
```suggestion
                failure_messages = validate_exporters(tracker.exporters, tracker_info)
```

2025-01-14 14:50 UTC, gmuloc commented on anta/input_models/flow_tracking.py
> +        InActive Timeout: 60000 Active Interval: 300000
```suggestion
        Inactive Timeout: 60000, Active Interval: 300000
```

2025-01-15 09:40 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
>          Failure message if any exporter configuration does not match.
Updated

2025-01-15 09:40 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +    failed_log = []
Updated

2025-01-15 09:40 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +    """Verifies the hardware flow tracking.
Updated

2025-01-15 09:41 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +        - All Hardware flow tracking is running.
Checking weather the hardware flow tracking is running or not on device

2025-01-15 09:42 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +    commands: ClassVar[list[AntaCommand | AntaTemplate]] = [AntaCommand(command="show flow tracking hardware", revision=2)]
Just updated to latest

2025-01-15 09:42 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +        - The specified input tracker is not active.
Updated. Thanks!!

2025-01-15 09:43 UTC, vitthalmagadum commented on anta/input_models/flow_tracking.py
> +        return f"InActive Timeout: {self.on_inactive_timeout} Active Interval: {self.on_interval}"
Updated

2025-01-15 09:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +            failed_log.append(f"Exporter: {exporter_name} - Incorrect template interval - Expected: {exporter.template_interval} Actual: {template_interval}")
Updated

2025-01-15 09:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +                        f"{tracker} {tracker.record_export} - Incorrect durations - InActive Timeout: {act_inactive} OnActive Interval: {act_interval}"
Updated

2025-01-15 09:43 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +        - All Hardware flow tracking is running.
you need to reword `Hardware flow tracking is running` - remove the `All`

2025-01-15 09:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +                failed_log = validate_exporters(tracker.exporters, tracker_info)
Updated

2025-01-15 09:43 UTC, vitthalmagadum commented on anta/input_models/flow_tracking.py
> +        InActive Timeout: 60000 Active Interval: 300000
Updated

2025-01-15 14:54 UTC, gmuloc requested changes
please move back revision to 1

2025-01-15 16:33 UTC, vitthalmagadum commented
> please move back revision to 1

Reverted to revision 1.
Thanks!!

2025-01-21 21:45 UTC, gmuloc requested changes

2025-01-21 21:45 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +        - Confirms that the specified input tracker is active.
```suggestion
        - Confirms that the tracker is active.
```

2025-01-21 21:45 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +        - For each specified flow tracker:
```suggestion
        - For any specified flow tracker:
```

2025-01-21 21:45 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +                        f"{tracker}, {tracker.record_export} - Incorrect durations - Inactive Timeout: {act_inactive}, OnActive Interval: {act_interval}"
```suggestion
                        f"{tracker}, {tracker.record_export} - Incorrect timers - Inactive Timeout: {act_inactive}, OnActive Interval: {act_interval}"
```

2025-01-22 03:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +        - Confirms that the specified input tracker is active.
Updated.

2025-01-22 03:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +        - For each specified flow tracker:
Updated.

2025-01-22 03:43 UTC, vitthalmagadum commented on anta/tests/flow_tracking.py
> +                        f"{tracker}, {tracker.record_export} - Incorrect durations - Inactive Timeout: {act_inactive}, OnActive Interval: {act_interval}"
Updated.

2025-01-28 13:42 UTC, gmuloc commented on anta/tests/flow_tracking.py
> +    """Verifies the hardware flow tracking configuration.
```suggestion
    """Verifies the hardware flow tracking state.
```

2025-01-28 13:43 UTC, gmuloc approved these changes
once CI succeeds

2025-01-28 13:51 UTC, gmuloc approved these changes

2025-01-28 14:04 UTC, merged