fix(anta.tests): VerifySpecificPath testcase with the latest changes
aristanetworks/anta pull request #965
Opened 2024-12-13 08:19 UTC by geetanjalimanegslab

# Description
Refactoring PathSelection (VerifySpecificPath) tests module to address the following issues:

- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-12-26 04:17 UTC, vitthalmagadum requested changes

2024-12-30 17:09 UTC, vitthalmagadum approved these changes

2025-01-14 15:01 UTC, gmuloc commented on anta/tests/path_selection.py
> +                self.result.is_failure(f"{router_path} - Path not found")
```suggestion
                self.result.is_failure(f"{router_path} - No path matching the source and destination found.")
```

2025-01-14 15:03 UTC, gmuloc commented on anta/tests/path_selection.py
> +            expected_state = ["ipsecEstablished", "routeResolved"]
do you need this variable? why not just put it directly in line 153?

2025-01-14 15:04 UTC, gmuloc commented on anta/tests/path_selection.py
> +                self.result.is_failure(f"{router_path} - Telemetry state inactive")
```suggestion
                self.result.is_failure(f"{router_path} - Telemetry state inactive for this path")
```

2025-01-21 21:59 UTC, gmuloc requested changes

2025-01-21 21:59 UTC, gmuloc commented on anta/tests/path_selection.py
> +    * Success: The test will pass if the path state under router path selection is either 'IPsecEstablished' or 'Resolved'
```suggestion
    * Success: The test will pass if the path state under router path-selection is either 'IPsecEstablished' or 'Resolved'
```

2025-01-21 21:59 UTC, gmuloc commented on anta/tests/path_selection.py
> +    * Failure: The test will fail if router path selection is not configured, the path state is not 'IPsec established' or 'Resolved',
```suggestion
    * Failure: The test will fail if router path selection or the peer is not configured or if the path state is not 'IPsec established' or 'Resolved',
```

2025-01-21 21:59 UTC, gmuloc commented on anta/tests/path_selection.py
> +        DpsPath: ClassVar[type[DpsPath]] = DpsPath
```suggestion
        RouterPath: ClassVar[type[DpsPath]] = DpsPath
        """To maintain backward compatibility."""
```

2025-01-28 14:04 UTC, gmuloc approved these changes

2025-01-28 14:04 UTC, gmuloc commented on anta/tests/path_selection.py
> +            # If the expected and actual source and destination address of the path group are not matched, test fails.
```suggestion
            #  Source and destination address do not match, the test fails.
```

2025-01-28 14:34 UTC, merged