feat(anta): Added testcase to validate the STP disabled VLANs
aristanetworks/anta pull request #972
Opened 2024-12-19 17:09 UTC by geetanjalimanegslab

# Description
This test performs the following checks:
        1. Verifies that the STP is configured.
        2. Verifies that the specified VLAN is present on the device.
        3. Verifies that the STP is disabled for the specified VLANs.

    Expected Results
    ----------------
    * Success: The test will pass if STP is disabled for the specified VLANs.
    * Failure: The test will fail, if STP is enabled for the specified VLANs

Fixes # (issue id) #862 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-12-24 12:11 UTC, vitthalmagadum requested changes

2024-12-26 11:42 UTC, vitthalmagadum commented on anta/tests/stp.py
> +    * Failure: The test will fail, if STP is enabled for the specified VLANs.
* Success: The test will pass if all of the following conditions are met:
      - STP is properly configured on the device.
      - The specified VLAN(s) exist on the device.
      - STP is confirmed to be disabled for all the specified VLAN(s).

2024-12-30 16:43 UTC, vitthalmagadum approved these changes
Please update succes and failure in docstring.

2024-12-31 11:16 UTC, vitthalmagadum approved these changes
LGTM

2024-12-31 12:33 UTC, carl-baillargeon approved these changes
LGTM. I will push some minor changes to docstrings. Thank you

2024-12-31 12:33 UTC, carl-baillargeon commented on anta/tests/stp.py
> +        2. Verifies that the specified VLAN is exist on the device.
```suggestion
        2. Verifies that the specified VLAN(s) exist on the device.
```

2024-12-31 12:33 UTC, carl-baillargeon commented on anta/tests/stp.py
> +        - The specified VLAN(s) not exist on the device.
```suggestion
        - The specified VLAN(s) do not exist on the device.
```

2024-12-31 12:33 UTC, carl-baillargeon commented on anta/tests/stp.py
> +        - STP is confirmed to be enabled for any of the specified VLAN(s).
```suggestion
        - STP is enabled for any of the specified VLAN(s).
```

2024-12-31 12:33 UTC, carl-baillargeon commented on anta/tests/stp.py
> +        """List of STP disabled VLAN(s)"""
```suggestion
        """List of STP disabled VLAN(s)."""
```

2024-12-31 12:33 UTC, carl-baillargeon commented on tests/units/anta_tests/test_stp.py
> +        "name": "failure-stp-disabled-vlans",
```suggestion
        "name": "failure-vlans-enabled",
```

2024-12-31 12:33 UTC, carl-baillargeon commented on tests/units/anta_tests/test_stp.py
> +        "name": "failure-stp-disabled-vlans-not-found",
```suggestion
        "name": "failure-vlans-not-found",
```

2024-12-31 12:33 UTC, carl-baillargeon commented on tests/units/anta_tests/test_stp.py
> +        "name": "success-stp-disabled-vlans",
```suggestion
        "name": "success",
```

2024-12-31 13:40 UTC, merged