Issue_864:Added test case to verify dynamic vlans source
aristanetworks/anta pull request #978
Opened 2024-12-24 06:13 UTC by geetanjalimanegslab

# Description

This test performs the following checks for each specified routerpath:
        1. Verifies that the dynamic VLANs are configured.
        2. Verifies that the dynamic VLANs are active only within the expected source.

Fixes #864 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-12-24 11:04 UTC, vitthalmagadum requested changes

2024-12-24 11:04 UTC, vitthalmagadum commented on tests/units/anta_tests/test_vlan.py
> +        "inputs": {"source": ["evpn", "mlagsync"]},
I do not see any dynamic VLANs with the input source `mlagsync`, yet the test passes.

2024-12-30 16:55 UTC, vitthalmagadum requested changes

2024-12-30 16:55 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +    *Success: The test will pass if all of the following conditions are met:
Please update this as unordered list.

2024-12-30 16:55 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +          all_source_dynamic_vlans: False
```suggestion
          strict: False
```

2024-12-30 16:55 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +        """Flag to check that all designated sources should have dynamic VLAN(s), Defaults to `False`"""
```suggestion
        strict: bool = False
        """If True, requires exact match of the provided dynamic VLAN sources, Defaults to `False`"""
```

2024-12-30 16:55 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +            self.result.is_failure(f"Dynamic VLAN(s) all source are not in {str_expected_source} Actual: {str_actual_source}")
Update this as well

2024-12-31 08:01 UTC, geetanjalimanegslab commented on anta/tests/vlan.py
> +        source: list[str]
As discussed keeping as it is.

2025-01-07 09:48 UTC, vitthalmagadum approved these changes

2025-01-07 20:22 UTC, carl-baillargeon requested changes

2025-01-07 20:22 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        if self.inputs.strict and sorted(actual_source) != (expected_source):
This could lead to false negatives if `expected_source` is unsorted.

2025-01-07 20:22 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Can you clarify the intent of the test?

It could be difficult for users to know which services will appear in the output. Also, a service (or source) being present in the dynamic VLANs output just means it's registered as a potential consumer and having no VLANs allocated (empty `vlanIds` list) doesn't necessarily mean it's an issue. Example: EVPN being "activated" but showing an empty `vlanIds` list is perfectly normal if it doesn't need any dynamic VLANs.

If the goal is to check that the provided services have dynamic VLANs registered, the test logic could be simplified a lot by looping over the input sources list, check if the source is present, if it is check if its `vlanIds` list is not empty.

2025-01-08 02:11 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
The actual test criteria is `If there are any dynamic VLANs, then these should only have source of "evpn" or "mlagsync" ie. all other sources must be "NONE"`. 
We are taking the sources as input and providing an option for exact match. On the other hand, if strict is set to False(default option), the test will pass as long as the dynamic VLANs are assigned to any of the input sources.

2025-01-08 02:52 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Ok in that case we need to update the docstring and logic to reflect this because, in my opinion, a service with an empty `vlanIds` list doesn't mean it's not configured/enabled. It just means the service doesn't use any dynamic VLANs.

The test should pass if all provided source(s) have dynamic VLANs registered (`vlanIds` not empty), if not, we just say there are no dynamic VLANs for the source(s) concerned. If strict is set, the test would fail if other sources (not provided by the user) have dynamic VLANs registered.

2025-01-08 03:02 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Logic: 

1. Strict: False
- If all provided source(s) have dynamic VLANs registered, Test should pass
- If not then passing the test as there are no dynamic VLANs for the source(s) concerned.
- If dynamic vlans are assigned to sources other than provided, Test should fail.

2. Strict: True
- If all provided source(s) have dynamic VLANs registered, Test should pass
- If not, Then test should fail saying dynamic vlans are not assigned to given sources.
- If dynamic vlans are assigned to sources other than provided, Test should fail.

2025-01-08 03:12 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Apologies if I was not super clear. Here's what I have in mind:

1. Strict: False
- If all provided source(s) have dynamic VLANs registered, test should pass.
- If not, then test should fail saying dynamic VLANs are not assigned to given sources.
- If dynamic VLANs are assigned to sources other than provided, test should pass (we don't care about other sources not provided by the user, we just explicity check the provided ones).
2. Strict: True
- If all provided source(s) have dynamic VLANs registered, test should pass.
- If not, then test should fail saying dynamic VLANs are not assigned to given sources.
- If dynamic VLANs are assigned to sources other than provided, test should fail (we do care about other sources now, we are not expecting other dynamic VLANs on other sources).

2025-01-08 03:20 UTC, vitthalmagadum commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Thanks @carl-baillargeon !!!

2025-01-14 05:13 UTC, geetanjalimanegslab commented on anta/tests/vlan.py
> +        if self.inputs.strict and sorted(actual_source) != (expected_source):
Thanks for the suggestion @carl-baillargeon ,
Addressed.

2025-01-14 05:14 UTC, geetanjalimanegslab commented on anta/tests/vlan.py
> +        model_config = ConfigDict(extra="forbid")
Yes. Correct, removed
Thanks!

2025-01-14 05:16 UTC, geetanjalimanegslab commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are enabled for all designated sources.
Thanks! @carl-baillargeon  Updated testcase as per the above mentioned logic.

2025-01-14 05:17 UTC, carl-baillargeon requested changes

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +    This test performs the following checks for specified dynamic VLAN(s):
```suggestion
    This test performs the following checks for each specified VLAN source:
```

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - The dynamic VLAN(s) are enabled on all the designated sources and disabled for non designated sources.
```suggestion
      1. Validates source exists in dynamic VLAN table.
      2. Verifies at least one VLAN is allocated to the source.
      3. When strict mode is enabled (`strict: true`), ensures no other sources have VLANs allocated.
```

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - In strict mode, The dynamic VLAN(s) are enabled on all the designated sources and disabled for non designated sources.
```suggestion
        - Each specified source exists in dynamic VLAN table.
        - Each specified source has at least one VLAN allocated.
        - In strict mode: No other sources have VLANs allocated.
```

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - In strict mode, dynamic VLAN(s) are disabled on any of the designated sources. or enabled for non designated sources.
```suggestion
        - Specified source not found in configuration.
        - Source exists but has no VLANs allocated.
        - In strict mode: Non-specified sources have VLANs allocated.
```

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        """The dynamic VLAN(s) source list."""
```suggestion
        """The dynamic VLAN source list."""
```

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +        - Dynamic VLAN(s) are not configured on the device.
Let's remove this.

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +            return
We don't need this. We should instead provide a failure message saying that the specified source is not found in the configuration.

2025-01-14 05:17 UTC, carl-baillargeon commented on anta/tests/vlan.py
> +            self.result.is_failure(f"Dynamic VLAN(s) sources mismatch - Expected: {str_expected_sources} Actual: {str_actual_sources}")
We should be more precise in the failure messages and say that a specified source doesn't have any VLAN allocated.

2025-01-14 13:54 UTC, merged