WIP: idempotency of setup logger
aristanetworks/anta pull request #981
Opened 2024-12-24 15:56 UTC by gmuloc

# Description

Fixes # (issue id)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2025-01-02 10:55 UTC, mtache requested changes
Maybe do the same logic for the FileHandler?

2025-01-02 11:22 UTC, gmuloc commented
> Maybe do the same logic for the FileHandler?

maybe don't call the funciton multiple time with the same file? :p

2025-01-02 22:05 UTC, carl-baillargeon approved these changes
Minor suggestion on variable name otherwise LGTM, tested locally:
![image](https://github.com/user-attachments/assets/48b52320-5f35-4dd7-9443-7432122bd44f)

Thank you for this, a lot faster now!!

2025-01-02 22:05 UTC, carl-baillargeon commented on anta/logger.py
> +    maybe_add_rich_handler = True
```suggestion
    needs_rich_handler = True
```

2025-01-03 09:24 UTC, mtache commented
> > Maybe do the same logic for the FileHandler?
> 
> maybe don't call the function multiple times with the same file? :p

This point of view is also valid for RichHandler, nevertheless we are making it idempotent.
I think this function should behave in a similar way for RichHandler and FileHandler (and it should have been idempotent from day 1).

From our unit test issue, if I write unit tests with a file as env var and I use CliRunner, I would log multiple times in the same file.

2025-01-03 09:28 UTC, gmuloc commented
> > > Maybe do the same logic for the FileHandler?
> > 
> > 
> > maybe don't call the function multiple times with the same file? :p
> 
> This point of view is also valid for RichHandler, nevertheless we are making it idempotent. I think this function should behave in a similar way for RichHandler and FileHandler (and it should have been idempotent from day 1).

Agreed

> 
> From our unit test issue, if I write unit tests with a file as env var and I use CliRunner, I would log multiple times in the same file.

Thats really a unit test problem

2025-01-03 09:31 UTC, gmuloc commented on anta/logger.py
> +    # Add FileHandler if file is provided and same File Handler is not already present
```suggestion
    # Add FileHandler if file is provided and same FileHandler is not already present
```

2025-01-03 09:32 UTC, mtache commented
NB for later:
we should not modify the root logger but an anta logger. Right way to implement that would be to delete all handlers of the anta logger at the beginning of the function.
We used root logger to have logs from other libraries, maybe we could modify specific loggers (httpx, asyncio) instead when in ANTA_DEBUG mode.

2025-01-06 18:56 UTC, mtache approved these changes

2025-01-06 18:56 UTC, merged